location: eastus
name: natyaca
properties:
  environmentId: "/subscriptions/9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f/resourceGroups/natyenv/providers/Microsoft.App/managedEnvironments/natyenv"
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 3000
  template:
    containers:
      - image: natyaca.azurecr.io/natyaca:${{ GITHUB_SHA }}
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 3
      type: "Microsoft.App/containerApps"



