apiVersion: '2022-05-01'
kind: ContainerApp
location: eastus
name: natyaca
properties:
  environmentId: "/subscriptions/9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f/resourceGroups/natyenv/providers/Microsoft.App/managedEnvironments/natyenv"
  configuration:
    secrets:
      - name: azure-client-id
        value: "${{AZURE_CLIENT_ID}}"
      - name: azure-client-secret
        value: "${{AZURE_CLIENT_SECRET}}"
    activeRevisionsMode: "Multiple"
    ingress:
      external: true
      targetPort: 3000
  template:
    containers:
      - name: natyaca-container
        image: natyacr.azurecr.io/natyaca:${{GITHUB_SHA}}
        env:
          - name: AZURE_CLIENT_ID
            secretRef: azure-client-id
          - name: AZURE_CLIENT_SECRET
            secretRef: azure-client-secret
        resources:
          cpu: 0.5
          memory: "1Gi"
    scale:
      minReplicas: 1
      maxReplicas: 3
tags: {}
type: Microsoft.App/containerApps


