---
name: natyaca
type: Microsoft.App/containerApps
location: EastUS
properties:
  managedEnvironmentId: /subscriptions/9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f/resourceGroups/natyenv/providers/Microsoft.App/managedEnvironments/natyenv
  configuration:
    secrets: []
  template:
    containers:
      - name: nginx
        image: nginx:latest
        resources:
          cpu: "0.5"
          memory: "1Gi"
        env:
          - name: PORT
            value: "80"
    scale:
      minReplicas: 1
      maxReplicas: 3





